project_name: bookimport

before:
  hooks:
    - go mod tidy

builds:
  - id: bookimport
    binary: bookimport
    gcflags:
      - all=-l -B
    ldflags:
      - -s -w
      - -X github.com/jianyun8023/bookimport/cmd.gitVersion={{ .Version }}
      - -X github.com/jianyun8023/bookimport/cmd.gitCommit={{ .Commit }}
      - -X github.com/jianyun8023/bookimport/cmd.buildDate={{ .Date }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: arm64

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^web:'
      - '^build:'

archives:
  - id: bookimport
    builds:
      - bookimport
    format: tar.gz
    wrap_in_directory: "true"
    format_overrides:
      - goos: windows
        format: zip

release:
  draft: true

snapshot:
  name_template: "{{ incminor .Version }}-next"